spring:
  profiles:
    active: test
  application:
    name: message-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/dataeditormessageservice?serverTimezone=UTC
    username: root
    password:

server:
  port: 8094


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: "${EUREKA_URI:http://localhost:8101/eureka}"
    instance:
      preferIpAddress: true
